### ISSUE TITLE
Unpredictable return statement

### ISSUE THREAD

**Issue by clayrisser** [clayrisser/react-ast#2]
```ts
      <FunctionDeclaration
        name="add"
        params={[<Param key="a">a</Param>, <Param key="b">b</Param>]}
        returnStatement="result"
      >
        <Code>const result=a+b</Code>
      </FunctionDeclaration>

```

The jsx above throws the following error

```
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
SyntaxError: Unexpected token (6:10)
  4 | 
  5 | function add(a, b) {
> 6 |   return return 'result';;
    |          ^
  7 |   const result = a + b;
  8 | }
    at e (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/parser-babylon.js:1:282)
    at Object.parse (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/parser-babylon.js:1:262260)
    at Object.parse (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:9739:19)
    at coreFormat (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:13252:23)
    at format (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:13526:12)
    at ~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:44207:15
    at Object.format (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:44226:12)
    at render (~/Projects/react-gtk/node_modules/.pnpm/registry.npmjs.org/react-ast/0.1.26/node_modules/react-ast/src/render.ts:45:21)
    at ~/Projects/react-gtk/packages/generate/src/actions/generate.tsx:14:16
Makefile:102: recipe for target 'start' failed
make: *** [start] Error 1

```

**Comment by clayrisser** [comment]
This issue is fixed with the new refactor.
